services:

  db:
    image: mariadb:latest
    container_name: arduino-dcmotor-db
    restart: always
    env_file:
      - ./backend/.env
    environment:
      MARIADB_ROOT_PASSWORD: "admin1234"
    ports:
      - "3306:3306"
    networks:
      - arduino_dcmotor_network
    volumes:
      - ./backend/src/config/db-init.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - mariadb_volume:/var/lib/mysql

  apache:
    image: arduino-dcmotor-apache-img
    container_name: arduino-dcmotor-apache
    build:
      context: .
      dockerfile: apache.dockerfile
      args:
        INIT_DB_FROM_SCRATCH: "false"
    env_file:
      - ./backend/.env
    environment:
      MARIADB_HOST: "db"
    ports:
      - "80:80"
    networks:
      - arduino_dcmotor_network
    depends_on:
      - db

  websocket:
    image: arduino-dcmotor-websocket-img
    container_name: arduino-dcmotor-websocket
    build:
      context: .
      dockerfile: websocket.dockerfile
    ports:
      - "8080:8080"
    networks:
      - arduino_dcmotor_network

networks:
  arduino_dcmotor_network:
    name: arduino_dcmotor_network
    driver: bridge

volumes:
  mariadb_volume:
    name: arduino_dcmotor_mariadb